### ISSUE TITLE
SHACL validation

### ISSUE THREAD

**Issue by veleda** [Sjofartsdirektoratet/Simulator#9]
* Take a look at Person instance data from Fred. 
* Transform to RDF.
* Connect to SHACL engine in TopBraid via API.
  * Find out how it works. 
* Run SHACL validation on Person instance data. 
  * instance data must be typed as a certificate class like the one we want to validate against (e.g. `rdf:type sdir:D10`).
* Capture validation report (as JSON-LD). Explore the results. 

Note:
Connect with Fred on where RDF-transformation of instance data is going to be implemented and what output he prefer from the validation engine.

**Comment by christinekaush** [comment]
Successful connection to SHACL engine in TopBraid using Postman
